name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
      - run: python -m venv venv && venv/bin/activate && pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'
      - run: venv/bin/activate && tox -e lint
